global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ingestor"
    static_configs:
      - targets: ["host.docker.internal:9881"]

  - job_name: "analytics"
    static_configs:
      - targets: ["host.docker.internal:9882"]

  - job_name: "processor"
    static_configs:
      - targets: ["host.docker.internal:9883"]

  - job_name: "retention"
    static_configs:
      - targets: ["host.docker.internal:9884"]
